# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/backup_naus.sh:/usr/local/bin/backup_naus.sh
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/populate.sql:/docker-entrypoint-initdb.d/populate.sql

volumes:
  db_data:

